import { Center, Container, Flex, Text } from '@chakra-ui/layout'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../common/Navbar'


export default function Home() {
  return (
    <>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Navbar></Navbar>
        <Container >
          <Text color="black">Something New</Text>
        </Container>
      </main>
    </>
  )
}
