import { Box, Center, Container, Flex, Text } from '@chakra-ui/layout'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import Navbar from '../common/Navbar'


export default function Home() {

  useEffect(() => {
    fetch('https://www.boredapi.com/api/activity')
    .then(data => {
      console.log(data)
    })

    
  })
  return (
    <>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar></Navbar>
        <Container m={0} p={0} >
          <Flex>
            <Box bg="red" h="100vh" w="20vh" minW="200px"></Box>
          </Flex>
        </Container>
      </main>
    </>
  )
}
